---
- name: setup osx defaults
  command: "{{ role_path }}/files/osx-defaults.sh"
  changed_when: false

# https://www.jamf.com/jamf-nation/discussions/10576/menu-bar-customization

# - name: add volume status to menu
#   command: open "/System/Library/CoreServices/Menu Extras/Volume.menu"

# - name: display turns off after 45 minutes on a/c power
#   command: pmset -c displaysleep 45
#   become: yes
