---
- name: create temporary install directory for oh-my-zsh
  tempfile:
    state: directory
    prefix: oh-my-zsh
  register: tempdir

- name: get oh-my-zsh install script
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: "{{ tempdir.path }}/install.sh"

- name: execute oh my zsh setup script
  command: "sh {{ tempdir.path }}/install.sh"

- name: check for zsh binary path
  shell: which zsh
  register: zsh_path
  changed_when: false

- name: ensure zsh is an allowable shell
  lineinfile:
    path: /etc/shells
    regexp: "{{ zsh_path.stdout | regex_escape }}"
    insertafter: EOF
    state: present
    line: "{{ zsh_path.stdout }}"
  become: true

- name: setting zsh as the default shell
  shell: "chsh --shell {{ zsh_path.stdout }} {{ ansible_user  }}"
  become: true
